---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  From the blog post, Visualize your Amazon Lookout for Metrics Anomaly Results, this script will
  create the Lambda Function and its Alert.

Parameters:

  LammbdaLayerPandasArn:
    Description: >
      pandas layer ARN from https://github.com/keithrozario/Klayers/tree/master/deployments/python3.8/arns. 
      Modify only if necessary.
    Type: String
    Default: "arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-pandas:38"

  CodeS3BucketName:
    Description: S3 Bucket location for related code
    NoEcho: true
    Type: String
    Default: https://lookoutformetricsbucket.s3.amazonaws.com/
 
Resources:

  L4MLambdaExecutionRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: L4MLambdaExecutionRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies: 
        - PolicyName: L4MTest
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: Allow
                Action: lookoutmetrics:*
                Resource: "*"

  L4MLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "L4MVersion3/lambda_function.lambda_handler"
      Role: !GetAtt L4MLambdaExecutionRole.Arn
      PackageType: Zip
      Code:
        S3Bucket: !ImportValue CodeS3BucketName
        S3Key: "next_steps/l4m2quicksight/src/L4MVersion3.zip"
      Layers:
        - !Ref LammbdaLayerPandasArn
      Runtime: python3.8
      Timeout: 5
      TracingConfig:
        Mode: Active

  L4MDetectorLambdaAlertRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: L4MDetectorLambdaAlertRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lookoutmetrics.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies: 
        - PolicyName: L4MTest
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt L4MLambdaFunction.Arn

  L4MDetectorLambdaAlert:
    Type: AWS::LookoutMetrics::Alert
    Properties:
      Action: 
        LambdaConfiguration: 
          LambdaArn: !GetAtt L4MLambdaFunction.Arn
          RoleArn: !GetAtt L4MDetectorLambdaAlertRole.Arn
      AlertDescription: "Detector Lambda Alert"
      AlertName: L4MDetectorLambdaAlert
      AlertSensitivityThreshold: 70
      AnomalyDetectorArn: !ImportValue L4MLiveDetectorArn
