---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
   From the blog post, Visualize your Amazon Lookout for Metrics Anomaly Results, this script will
   create the Amazon QuickSight Athena Data Source.

Parameters:

   UserName:
      Description: Enter your Amazon QuickSight username.
      Type: String

Resources:

   L4MQuickSightDataSource:
      Type: AWS::QuickSight::DataSource
      Properties: 
         AwsAccountId: !Ref AWS::AccountId
         DataSourceId: 'L4MQuickSightDataSource'
         Name: L4MQuickSightDataSource
         Type: 'ATHENA'
         DataSourceParameters:
            AthenaParameters:
               WorkGroup: primary #primary is the default workgroup
         Permissions:
            - Principal: !Sub 'arn:aws:quicksight:us-east-1:${AWS::AccountId}:user/default/${UserName}'
              Actions:
                - 'quicksight:DescribeDataSource'
                - 'quicksight:DescribeDataSourcePermissions'
                - 'quicksight:UpdateDataSource'
                - 'quicksight:UpdateDataSourcePermissions'
                - 'quicksight:DeleteDataSource'
                - 'quicksight:PassDataSource'
Outputs:

  L4MQuickSightDataSourceArn:
    Description: 'L4M QuickSight DataSource ARN'
    Value: !GetAtt L4MQuickSightDataSource.Arn
    Export:
        Name: 'L4MQuickSightDataSourceArn'

  L4MQuickSightPrincipalArn:
      Description: 'L4M QuickSight Permissions Principal ARN'
      Value: !Sub 'arn:aws:quicksight:us-east-1:${AWS::AccountId}:user/default/${UserName}'
      Export:
         Name: 'L4MQuickSightPrincipalArn'

